# Generated by Django 5.0.4 on 2024-07-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('expense_type', models.CharField(choices=[('Positive ', 'Positive'), ('Negative', 'Negative')], max_length=100)),
            ],
        ),
    ]
